# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-05-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grifo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('monto_cobro', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ControlTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('impte_vta_normal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impte_vta_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impte_tot_cobranza', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impte_tot_gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cuenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Operador')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('precio_cred', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('monto_cred', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('cobrado', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('cliente', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('precio_dscto', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('monto_dscto', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('lectura_lado_a', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('lectura_lado_b', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('gal_despachados', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('gal_descuento', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('vta_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gal_credito', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('vta_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gal_devueltos', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('gal_normal', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('vta_normal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ControlTurno')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Despacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ControlTurno')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Despacho'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Producto'),
        ),
        migrations.AddField(
            model_name='credito',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Despacho'),
        ),
        migrations.AddField(
            model_name='credito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifo.Producto'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Credito'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ControlTurno'),
        ),
    ]
