# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-05-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='monto_cobr',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
