# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-05-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_credito_monto_cobr'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlturno',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
