# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-05-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('razonsocial', models.CharField(blank=True, max_length=250, null=True)),
                ('ruc', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
            ],
            options={
                'ordering': ['razonsocial'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('lado_a', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('lado_b', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
            ],
        ),
    ]
